# Generated by Django 3.2.7 on 2021-09-30 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40, verbose_name='Title')),
                ('announce', models.CharField(max_length=256, verbose_name='Announce')),
                ('full_text', models.TextField(verbose_name='Full text')),
                ('image', models.ImageField(height_field=50, upload_to='uploads/', verbose_name='Image', width_field=50)),
                ('date', models.DateTimeField(verbose_name='Date')),
            ],
        ),
    ]
